In [ ]:
# installation of beautifulSoup4

!pip install requests beautifulSoup4 selenium

Requirement already satisfied: requests in c:\users\user\anaconda3\lib\site-packages (2.32.2)
Requirement already satisfied: beautifulSoup4 in c:\users\user\anaconda3\lib\site-packages (4.12.3)
Requirement already satisfied: selenium in c:\users\user\anaconda3\lib\site-packages (4.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\anaconda3\lib\site-packages (from requests) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\anaconda3\lib\site-packages (from requests) (2024.6.2)
Requirement already satisfied: soupsieve>1.2 in c:\users\user\anaconda3\lib\site-packages (from beautifulSoup4) (2.5)
Requirement already satisfied: trio~=0.17 in c:\users\user\anaconda3\lib\site-packages (from selenium) (0.29.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\user\anaconda3\lib\site-packages (from selenium) (0.12.2)
Requirement already satisfied: typing_extensions~=4.9 in c:\users\user\anaconda3\lib\site-packages (from selenium) (4.11.0)
Requirement already satisfied: websocket-client~=1.8 in c:\users\user\anaconda3\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\user\anaconda3\lib\site-packages (from trio~=0.17->selenium) (25.3.0)
Requirement already satisfied: sortedcontainers in c:\users\user\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: outcome in c:\users\user\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\user\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\user\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.16.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\user\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\user\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\user\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\user\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [ ]:
""""
- we get the range of the years we want to work with and store it in a year variable 

- the years range from 2023 - 2025
"""

years = list(range(2023,2026))

In [6]:
print (years)

[2023, 2024, 2025]

In [ ]:
## url to find the ratings table to scrape the data from the table 
team_ratings_url = "https://www.basketball-reference.com/leagues/NBA_{}_ratings.html"

In [13]:
import requests

In [ ]:

for year in years:
    url = team_ratings_url.format(year)
    data = requests.get(url)

    with open("team_ratings/{}.html".format(year), "w+", encoding='utf-8') as f:
        f.write(data.text)

In [2]:
from bs4 import BeautifulSoup

In [9]:
with open("team_ratings/2024.html", encoding='utf-8') as f:
    page = f.read()

In [10]:
soup = BeautifulSoup(page, "html.parser")

In [11]:
soup.find('tr', class_= "over_header").decompose()

In [16]:
ratings_table= soup.find(id="ratings")

In [3]:
import pandas as pd

In [24]:
ratings_2024 =pd.read_html(str(ratings_table))[0]

C:\Users\USER\AppData\Local\Temp\ipykernel_6864\627769708.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  ratings_2024 =pd.read_html(str(ratings_table))[0]

In [23]:
ratings_2024

,Rk,Team,Conf,Div,W,L,W/L%,MOV,ORtg,DRtg,NRtg,MOV/A,ORtg/A,DRtg/A,NRtg/A
0,1,Boston Celtics,E,A,64,18,0.780,11.34,124.23,112.51,11.71,10.74,123.81,112.70,11.11
1,2,Oklahoma City Thunder,W,NW,57,25,0.695,7.41,120.43,113.12,7.31,7.36,120.49,113.23,7.26
2,3,Minnesota Timberwolves,W,NW,56,26,0.683,6.45,116.63,109.98,6.65,6.38,116.53,109.95,6.57
3,4,Denver Nuggets,W,NW,57,25,0.695,5.26,119.49,114.05,5.44,5.23,119.60,114.20,5.40
4,5,New York Knicks,E,A,50,32,0.610,4.59,119.11,114.22,4.89,4.36,118.93,114.28,4.66
5,6,New Orleans Pelicans,W,SW,49,33,0.598,4.41,118.31,113.70,4.61,4.46,118.40,113.75,4.65
6,7,Los Angeles Clippers,W,P,51,31,0.622,3.28,119.75,116.51,3.24,3.41,119.97,116.59,3.37
7,8,Phoenix Suns,W,P,49,33,0.598,3.06,118.78,115.69,3.09,3.08,118.83,115.73,3.10
8,9,Golden State Warriors,W,P,46,36,0.561,2.61,118.67,115.95,2.72,2.77,118.76,115.89,2.87
9,10,Indiana Pacers,E,C,47,35,0.573,3.05,121.85,118.85,2.99,2.75,121.73,119.03,2.70
10,11,Philadelphia 76ers,E,A,47,35,0.573,3.05,117.79,114.76,3.02,2.51,117.50,115.01,2.49
11,12,Milwaukee Bucks,E,C,49,33,0.598,2.62,119.12,116.49,2.64,2.44,119.00,116.53,2.46
12,13,Sacramento Kings,W,P,46,36,0.561,1.74,117.68,116.01,1.67,2.29,117.91,115.68,2.23
13,14,Dallas Mavericks,W,SW,50,32,0.610,2.21,118.38,116.28,2.09,2.30,118.60,116.42,2.18
14,15,Cleveland Cavaliers,E,C,48,34,0.585,2.41,116.21,113.80,2.41,1.98,115.88,113.91,1.97
15,16,Orlando Magic,E,SE,47,35,0.573,2.02,114.36,112.26,2.10,1.48,113.95,112.40,1.55
16,17,Houston Rockets,W,SW,41,41,0.500,1.12,115.34,114.22,1.12,1.24,115.40,114.17,1.23
17,18,Miami Heat,E,SE,46,36,0.561,1.76,114.95,113.31,1.64,1.10,114.55,113.57,0.98
18,19,Los Angeles Lakers,W,P,47,35,0.573,0.60,116.69,116.21,0.47,1.07,117.00,116.04,0.95
19,20,Chicago Bulls,E,C,39,43,0.476,-1.44,115.83,117.46,-1.64,-1.77,115.71,117.66,-1.95
20,21,Atlanta Hawks,E,SE,36,46,0.439,-2.18,118.16,120.25,-2.09,-2.38,118.16,120.45,-2.29
21,22,Brooklyn Nets,E,A,32,50,0.390,-2.89,114.14,117.13,-2.99,-3.02,114.06,117.16,-3.11
22,23,Utah Jazz,W,NW,31,51,0.378,-4.89,116.38,121.39,-5.01,-4.22,116.85,121.18,-4.33
23,24,San Antonio Spurs,W,SW,22,60,0.268,-6.49,110.85,117.18,-6.32,-5.80,111.19,116.83,-5.64
24,25,Toronto Raptors,E,A,25,57,0.305,-6.44,113.14,119.68,-6.54,-6.45,113.04,119.57,-6.54
25,26,Memphis Grizzlies,W,SW,27,55,0.329,-7.00,108.12,115.30,-7.18,-6.57,108.28,115.02,-6.74
26,27,Portland Trail Blazers,W,NW,21,61,0.256,-9.02,109.34,118.60,-9.26,-8.29,109.65,118.16,-8.51
27,28,Detroit Pistons,E,C,14,68,0.171,-9.11,110.42,119.51,-9.09,-9.06,110.43,119.48,-9.05
28,29,Washington Wizards,E,SE,15,67,0.183,-9.29,111.12,120.22,-9.10,-9.29,111.11,120.21,-9.11
29,30,Charlotte Hornets,E,SE,21,61,0.256,-10.24,110.27,120.89,-10.63,-10.12,110.23,120.71,-10.48

"""
- using a For loop to get each team rating for each year
- use beautifulSoup html parser to get the content of the page
- append the tables into a dataframe
- write the dataframe into a csv file
"""

In [ ]:
dfs = []

for year in years:
    with open("team_ratings/{}.html".format(year), encoding='utf-8') as f:
        page = f.read()
    soup = BeautifulSoup(page, "html.parser")
    soup.find('tr', class_= "over_header").decompose()
    ratings_table= soup.find(id="ratings")
    rating =pd.read_html(str(ratings_table))[0]
    rating['Year'] = year

    dfs.append(rating)

C:\Users\USER\AppData\Local\Temp\ipykernel_13996\412996934.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  rating =pd.read_html(str(ratings_table))[0]
C:\Users\USER\AppData\Local\Temp\ipykernel_13996\412996934.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  rating =pd.read_html(str(ratings_table))[0]
C:\Users\USER\AppData\Local\Temp\ipykernel_13996\412996934.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  rating =pd.read_html(str(ratings_table))[0]

In [43]:
rating.head()

,Rk,Team,Conf,Div,W,L,W/L%,MOV,ORtg,DRtg,NRtg,MOV/A,ORtg/A,DRtg/A,NRtg/A,Year
0,1,Oklahoma City Thunder,W,NW,67,14,0.827,12.84,120.41,107.71,12.70,12.77,120.30,107.67,12.63,2025
1,2,Cleveland Cavaliers,E,C,64,17,0.790,9.75,122.21,112.47,9.74,8.98,122.06,113.09,8.98,2025
2,3,Boston Celtics,E,A,60,21,0.741,9.14,121.04,111.51,9.53,8.41,120.83,112.04,8.79,2025
3,4,Minnesota Timberwolves,W,NW,48,33,0.593,4.93,116.70,111.58,5.12,5.18,116.66,111.30,5.35,2025
4,5,Houston Rockets,W,SW,52,29,0.642,4.75,115.24,110.65,4.59,5.16,115.40,110.41,4.99,2025

In [49]:
ratings = pd.concat(dfs)

In [50]:
ratings.tail()

,Rk,Team,Conf,Div,W,L,W/L%,MOV,ORtg,DRtg,NRtg,MOV/A,ORtg/A,DRtg/A,NRtg/A,Year
25,26,Brooklyn Nets,E,A,26,55,0.321,-7.10,108.62,115.82,-7.20,-6.98,108.69,115.76,-7.07,2025
26,27,Utah Jazz,W,NW,17,64,0.210,-9.32,111.29,120.63,-9.34,-8.55,111.56,120.14,-8.58,2025
27,28,New Orleans Pelicans,W,SW,21,60,0.259,-9.36,110.52,120.08,-9.56,-8.67,110.76,119.63,-8.87,2025
28,29,Charlotte Hornets,E,SE,19,62,0.235,-9.14,107.52,116.81,-9.29,-9.22,107.53,116.91,-9.37,2025
29,30,Washington Wizards,E,SE,17,64,0.210,-12.60,106.66,119.15,-12.49,-12.29,106.82,119.00,-12.18,2025

In [47]:
ratings.to_csv("ratings.csv")

installation of webdriver to be able to make use of selenium

In [ ]:
%pip install webdriver-manager

Collecting webdriver-manager
  Using cached webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: requests in c:\users\user\anaconda3\lib\site-packages (from webdriver-manager) (2.32.2)
Requirement already satisfied: python-dotenv in c:\users\user\anaconda3\lib\site-packages (from webdriver-manager) (0.21.0)
Requirement already satisfied: packaging in c:\users\user\anaconda3\lib\site-packages (from webdriver-manager) (23.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\anaconda3\lib\site-packages (from requests->webdriver-manager) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\anaconda3\lib\site-packages (from requests->webdriver-manager) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\anaconda3\lib\site-packages (from requests->webdriver-manager) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\anaconda3\lib\site-packages (from requests->webdriver-manager) (2024.6.2)
Using cached webdriver_manager-4.0.2-py2.py3-none-any.whl (27 kB)
Installing collected packages: webdriver-manager
Successfully installed webdriver-manager-4.0.2

In [ ]:
%pip install lxml html5lib

Requirement already satisfied: lxml in c:\users\user\anaconda3\lib\site-packages (5.2.1)
Requirement already satisfied: html5lib in c:\users\user\anaconda3\lib\site-packages (1.1)
Requirement already satisfied: six>=1.9 in c:\users\user\anaconda3\lib\site-packages (from html5lib) (1.16.0)
Requirement already satisfied: webencodings in c:\users\user\anaconda3\lib\site-packages (from html5lib) (0.5.1)

In [59]:
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)

In [65]:
import time

player_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_per_game.html"
for year in years:
    url = player_stats_url.format(year)
    
    driver.get(url)
    driver.execute_script("window.scrollTo(1,10000)")
    time.sleep(2)
    
    
    html = driver.page_source
    with open("player/{}.html".format(year), "w+",  encoding='utf-8' ) as f:
        f.write(html)

In [21]:
from io import StringIO
import html5lib

- use of For loop to iterate through the years
- iterate through the years to get the players table
- use soup.find to select the class and id of the HTML section to scrape from
- append information into a data-frame
- store information in a csv file

In [7]:
dfs = []

for year in years:
    with open("player/{}.html".format(year), encoding='utf-8') as f:
        page = f.read()
    
    soup = BeautifulSoup( page, "html.parser")
    soup.find('tr', class_= "thead").decompose()
    player_table= soup.find(id="per_game_stats")
    player = pd.read_html(str(player_table))[0]
    player['Year'] = year

    dfs.append(player)

C:\Users\USER\AppData\Local\Temp\ipykernel_2300\2619629782.py:10: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\USER\AppData\Local\Temp\ipykernel_2300\2619629782.py:10: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\USER\AppData\Local\Temp\ipykernel_2300\2619629782.py:10: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]

In [8]:
player.head()

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Year
0,1,Shai Gilgeous-Alexander,26,OKC,PG,76,76,34.2,11.3,21.8,...,4.1,5.0,6.4,1.7,1.0,2.4,2.2,32.7,NaN,2025
1,2,Giannis Antetokounmpo,30,MIL,PF,67,67,34.2,11.8,19.7,...,9.7,11.9,6.5,0.9,1.2,3.1,2.3,30.4,NaN,2025
2,3,Nikola Jokić,29,DEN,C,70,70,36.7,11.2,19.5,...,9.9,12.7,10.2,1.8,0.6,3.3,2.3,29.6,NaN,2025
3,4,Luka Dončić,25,2TM,PG,50,50,35.4,9.2,20.5,...,7.4,8.2,7.7,1.8,0.4,3.6,2.5,28.2,NaN,2025
4,4,Luka Dončić,25,DAL,PG,22,22,35.7,9.8,21.2,...,7.6,8.3,7.8,2.0,0.4,3.4,2.6,28.1,NaN,2025

In [9]:
players = pd.concat(dfs)

In [10]:
players.head()

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Year
0,1,Joel Embiid,28,PHI,C,66,66,34.6,11.0,20.1,...,8.4,10.2,4.2,1.0,1.7,3.4,3.1,33.1,"MVP-1,DPOY-9,CPOY-5,AS,NBA1",2023
1,2,Luka Dončić,23,DAL,PG,66,66,36.2,10.9,22.0,...,7.8,8.6,8.0,1.4,0.5,3.6,2.5,32.4,"MVP-8,CPOY-8,AS,NBA1",2023
2,3,Damian Lillard,32,POR,PG,58,58,36.3,9.6,20.7,...,4.0,4.8,7.3,0.9,0.3,3.3,1.9,32.2,"CPOY-10,AS,NBA3",2023
3,4,Shai Gilgeous-Alexander,24,OKC,PG,68,68,35.5,10.4,20.3,...,4.0,4.8,5.5,1.6,1.0,2.8,2.8,31.4,"MVP-5,CPOY-7,AS,NBA1",2023
4,5,Giannis Antetokounmpo,28,MIL,PF,63,63,32.1,11.2,20.3,...,9.6,11.8,5.7,0.8,0.8,3.9,3.1,31.1,"MVP-3,DPOY-6,AS,NBA1",2023

In [11]:
players.to_csv("players.csv")

- use of For loop to iterate through the years
- iterate through the years to get the team stats table
- use soup.find to select the class and id of the HTML section to scrape from
- append information into a data-frame
- store information in a csv file

In [16]:
for year in years:
    team_stats_url="https://www.basketball-reference.com/leagues/NBA_{}.html"
    url = team_stats_url.format(year)
    
    data = requests.get(url)
    
    with open("team_stats/{}.html".format(year), "w+", encoding='utf-8') as f:
        f.write(data.text)

In [28]:
dfs =[]

for year in years:
    with open("team_stats/{}.html".format(year), encoding='utf-8') as f:
        page = f.read()
         
    soup = BeautifulSoup( page, "html.parser")
    soup.find('tr', class_= "thead").decompose()
    team_table= soup.find(id="divs_standings_E")
    team = pd.read_html(str(team_table))[0]
    team['Year'] = year
    team["Team"] = team["Eastern Conference"]
    del team["Eastern Conference"]
    dfs.append(team)
    
    soup = BeautifulSoup( page, "html.parser")
    soup.find('tr', class_= "thead").decompose()
    team_table= soup.find(id="divs_standings_W")
    team = pd.read_html(str(team_table))[0]
    team['Year'] = year
    team["Team"] = team["Western Conference"]
    del team["Western Conference"]
    dfs.append(team)

C:\Users\USER\AppData\Local\Temp\ipykernel_2300\1900206299.py:10: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\USER\AppData\Local\Temp\ipykernel_2300\1900206299.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\USER\AppData\Local\Temp\ipykernel_2300\1900206299.py:10: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\USER\AppData\Local\Temp\ipykernel_2300\1900206299.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\USER\AppData\Local\Temp\ipykernel_2300\1900206299.py:10: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\USER\AppData\Local\Temp\ipykernel_2300\1900206299.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]

In [29]:
teams = pd.concat(dfs)

In [30]:
teams

     W   L  W/L%    GB   PS/G   PA/G    SRS  Year                       Team
0   57  25  .695     —  117.9  111.4   6.38  2023            Boston Celtics*
1   54  28  .659   3.0  115.2  110.9   4.37  2023        Philadelphia 76ers*
2   47  35  .573  10.0  116.0  113.1   2.99  2023           New York Knicks*
3   45  37  .549  12.0  113.4  112.5   1.03  2023             Brooklyn Nets*
4   41  41  .500  16.0  112.9  111.4   1.59  2023            Toronto Raptors
..  ..  ..   ...   ...    ...    ...    ...   ...                        ...
13  52  30  .634     —  114.3  109.8   4.97  2025        Houston Rockets (2)
14  48  34  .585   4.0  121.7  116.9   4.79  2025      Memphis Grizzlies (8)
15  39  43  .476  13.0  114.2  115.4  -0.74  2025      Dallas Mavericks (10)
16  34  48  .415  18.0  113.9  116.7  -2.45  2025     San Antonio Spurs (13)
17  21  61  .256  31.0  109.8  119.3  -8.59  2025  New Orleans Pelicans (14)

[105 rows x 9 columns]

In [31]:
teams.to_csv("teams_division_standings.csv")

In [32]:
dfs =[]

for year in years:
    with open("team_stats/{}.html".format(year), encoding='utf-8') as f:
        page = f.read()
         
    soup = BeautifulSoup( page, "html.parser")
    soup.find('tr', class_= "thead").decompose()
    team_table= soup.find(id="confs_standings_E")
    team = pd.read_html(str(team_table))[0]
    team['Year'] = year
    team["Team"] = team["Eastern Conference"]
    del team["Eastern Conference"]
    dfs.append(team)
    
    soup = BeautifulSoup( page, "html.parser")
    soup.find('tr', class_= "thead").decompose()
    team_table= soup.find(id="confs_standings_W")
    team = pd.read_html(str(team_table))[0]
    team['Year'] = year
    team["Team"] = team["Western Conference"]
    del team["Western Conference"]
    dfs.append(team)

C:\Users\USER\AppData\Local\Temp\ipykernel_2300\1124329762.py:10: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\USER\AppData\Local\Temp\ipykernel_2300\1124329762.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\USER\AppData\Local\Temp\ipykernel_2300\1124329762.py:10: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\USER\AppData\Local\Temp\ipykernel_2300\1124329762.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\USER\AppData\Local\Temp\ipykernel_2300\1124329762.py:10: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\USER\AppData\Local\Temp\ipykernel_2300\1124329762.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]

In [33]:
teams = pd.concat(dfs)

In [34]:
teams

     W   L   W/L%    GB   PS/G   PA/G   SRS  Year                         Team
0   58  24  0.707     —  116.9  113.3  3.61  2023             Milwaukee Bucks*
1   57  25  0.695   1.0  117.9  111.4  6.38  2023              Boston Celtics*
2   54  28  0.659   4.0  115.2  110.9  4.37  2023          Philadelphia 76ers*
3   51  31  0.622   7.0  112.3  106.9  5.23  2023         Cleveland Cavaliers*
4   47  35  0.573  11.0  116.0  113.1  2.99  2023             New York Knicks*
..  ..  ..    ...   ...    ...    ...   ...   ...                          ...
10  36  46  0.439  32.0  113.6  116.6 -2.55  2025            Phoenix Suns (11)
11  36  46  0.439  32.0  110.9  113.9 -2.67  2025  Portland Trail Blazers (12)
12  34  48  0.415  34.0  113.9  116.7 -2.45  2025       San Antonio Spurs (13)
13  21  61  0.256  47.0  109.8  119.3 -8.59  2025    New Orleans Pelicans (14)
14  17  65  0.207  51.0  111.9  121.2 -8.51  2025               Utah Jazz (15)

[90 rows x 9 columns]

In [35]:
teams.to_csv("teams_conf_standings.csv")